<?php

namespace App\Services;

use App\Models\BossIcon;
use App\Models\Event;

/**
 * Which picture belongs to which boss, and where it comes from.
 *
 * Two sources, in this order:
 *
 *  1. **An admin's override** (`boss_icons`), which is a URL — normally an
 *     OSRS Wiki image. This exists so a gap can be filled without a deploy:
 *     Aggy (Mad Angel) and Bran (The Royal Titans) have a pet on the wiki that
 *     the icon package has not shipped, and waiting on an upstream release for
 *     a picture is the wrong shape.
 *  2. **The committed pet sprite** under public/images/osrs/bosses/, written by
 *     scripts/extract-osrs-icons.mjs from @dava96/osrs-icons.
 *
 * Neither means no icon, which is a real answer: eight of these bosses drop no
 * pet at all. A wrong icon would be worse than none.
 *
 * The existence check is a filesystem stat rather than a second manifest,
 * because the files ARE the manifest — one source of truth, and no list to
 * fall out of step with the directory it describes.
 */
class BossIconService
{
    /** Where the extraction script writes, relative to public/. */
    private const SPRITE_DIR = 'images/osrs/bosses';

    /**
     * Every boss, with the icon it would render and where that came from.
     *
     * Shaped for the admin screen, which has to show all 71 whether they have
     * an icon or not — the ones without are exactly what somebody opens that
     * page to fix.
     *
     * @return array<int, array{metric: string, url: string|null, source: string, suggested: string|null}>
     */
    public function all(): array
    {
        $rows = BossIcon::get(['metric', 'icon_url', 'suggested_url'])->keyBy('metric');

        return array_map(function (string $metric) use ($rows) {
            $row = $rows->get($metric);
            $sprite = $this->spriteUrl($metric);

            return [
                'metric' => $metric,
                'url' => $row?->icon_url ?? $sprite,
                'source' => match (true) {
                    $row?->icon_url !== null => 'custom',
                    $sprite !== null => 'sprite',
                    default => 'none',
                },
                // Carried alongside rather than folded into `url`: a proposal
                // is not in force, and the page has to be able to show both
                // what is showing now and what is being offered instead.
                'suggested' => $row?->suggested_url,
            ];
        }, Event::BOSS_METRICS);
    }

    /**
     * Only the overrides, keyed by metric — what the browser needs to know.
     *
     * Deliberately not the whole map: the committed sprites are already known
     * client-side (Support/bossIcons.js, generated by the same script that
     * writes them), so shipping all 71 URLs on every page would be sending
     * the browser something it can already work out. This is normally empty
     * or a couple of entries.
     *
     * @return array<string, string>
     */
    public function overrides(): array
    {
        return BossIcon::pluck('icon_url', 'metric')->all();
    }

    /** The committed sprite for a boss, or null when there is not one. */
    public function spriteUrl(string $metric): ?string
    {
        return file_exists(public_path(self::SPRITE_DIR."/{$metric}.png"))
            ? '/'.self::SPRITE_DIR."/{$metric}.png"
            : null;
    }
}
