// eslint.config.mjs
// @ts-check
import { createConfigForNuxt } from '@nuxt/eslint-config';
import eslintConfigPrettier from 'eslint-config-prettier';
import eslintPluginPrettier from 'eslint-plugin-prettier';

export default createConfigForNuxt({
  features: {
    stylistic: false,
    tooling: false,
  },
})
  .append({
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-multiple-empty-lines': ['error', { max: 1, maxBOF: 1, maxEOF: 1 }],

      'vue/block-order': ['error', { order: ['template', 'script', 'style'] }],

      'vue/component-api-style': ['error', ['script-setup']],

      'vue/block-lang': [
        'error',
        {
          script: { lang: ['ts'], allowNoLang: false },
        },
      ],

      'vue/html-indent': [
        'error',
        2,
        {
          attribute: 1,
          baseIndent: 1,
          closeBracket: 0,
          alignAttributesVertically: true,
          ignores: [],
        },
      ],

      'vue/html-closing-bracket-newline': [
        'error',
        {
          singleline: 'never',
          multiline: 'always',
        },
      ],

      'vue/padding-line-between-tags': [
        'error',
        [
          {
            blankLine: 'always',
            prev: '*',
            next: '*',
          },
        ],
      ],

      'vue/padding-line-between-blocks': ['error'],

      'vue/define-macros-order': [
        'error',
        {
          order: ['defineOptions', 'defineModel', 'defineProps', 'defineEmits', 'defineSlots'],
          defineExposeLast: true,
        },
      ],

      'vue/component-name-in-template-casing': [
        'error',
        'kebab-case',
        {
          registeredComponentsOnly: false,
          ignores: [],
        },
      ],

      'vue/prop-name-casing': ['error', 'camelCase'],

      'vue/max-attributes-per-line': [
        'error',
        {
          singleline: { max: 1 },
          multiline: { max: 1 },
        },
      ],

      'vue/first-attribute-linebreak': [
        'error',
        {
          singleline: 'ignore',
          multiline: 'below',
        },
      ],

      'vue/multiline-html-element-content-newline': [
        'error',
        {
          ignoreWhenEmpty: true,
          ignores: ['pre', 'textarea'],
          allowEmptyLines: true,
        },
      ],

      'import/order': [
        'error',
        {
          groups: [['builtin', 'external'], ['internal'], ['parent', 'sibling', 'index'], ['type']],
          'newlines-between': 'always',
          alphabetize: {
            order: 'asc',
            caseInsensitive: true,
          },
        },
      ],

      'prettier/prettier': 'error',
    },
  })
  .append({
    plugins: {
      prettier: eslintPluginPrettier,
    },
  })
  // Generated by `pnpm generate` from backend/schema.gql — formatting it here
  // would just be undone on the next codegen run, permanently reddening lint.
  .append({
    ignores: ['app/types/graphql.ts'],
  })
  // Disable ESLint rules that conflict with Prettier formatting
  .append(eslintConfigPrettier);
