/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const Head: typeof import('@inertiajs/vue3').Head
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineLocale: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale').defineLocale
  const defineShortcuts: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts').defineShortcuts
  const effectScope: typeof import('vue').effectScope
  const extendLocale: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale').extendLocale
  const extractShortcuts: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts').extractShortcuts
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const router: typeof import('@inertiajs/vue3').router
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAppConfig: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/vue/composables/useAppConfig.js').useAppConfig
  const useAttrs: typeof import('vue').useAttrs
  const useContentSearch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useContentSearch').useContentSearch
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useFileUpload: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useFileUpload').useFileUpload
  const useForm: typeof import('@inertiajs/vue3').useForm
  const useFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useFormField').useFormField
  const useId: typeof import('vue').useId
  const useKbd: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useKbd').useKbd
  const useModel: typeof import('vue').useModel
  const useOverlay: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay').useOverlay
  const usePage: typeof import('@inertiajs/vue3').usePage
  const useResizable: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useResizable').useResizable
  const useScrollShadow: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useScrollShadow').useScrollShadow
  const useScrollspy: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useScrollspy').useScrollspy
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useToast: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useToast').useToast
  const useTour: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useTour').useTour
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly Head: UnwrapRef<typeof import('@inertiajs/vue3')['Head']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineLocale: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale')['defineLocale']>
    readonly defineShortcuts: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts')['defineShortcuts']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly extendLocale: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale')['extendLocale']>
    readonly extractShortcuts: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts')['extractShortcuts']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly router: UnwrapRef<typeof import('@inertiajs/vue3')['router']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAppConfig: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/vue/composables/useAppConfig.js')['useAppConfig']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useContentSearch: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useContentSearch')['useContentSearch']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useFileUpload: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useFileUpload')['useFileUpload']>
    readonly useForm: UnwrapRef<typeof import('@inertiajs/vue3')['useForm']>
    readonly useFormField: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['useFormField']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useKbd: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useKbd')['useKbd']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useOverlay: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay')['useOverlay']>
    readonly usePage: UnwrapRef<typeof import('@inertiajs/vue3')['usePage']>
    readonly useResizable: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useResizable')['useResizable']>
    readonly useScrollShadow: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useScrollShadow')['useScrollShadow']>
    readonly useScrollspy: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useScrollspy')['useScrollspy']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useToast: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useToast')['useToast']>
    readonly useTour: UnwrapRef<typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/composables/useTour')['useTour']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}