/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UColorModeButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UContainer: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFooter: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Footer.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UHeader: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UMain: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPage: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Page.vue')['default']
    UPageCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UProgress: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_ba9c56692b3623567dd0b34284b6a13f/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
