<template>
    <u-page-section
        :title="title ?? undefined"
        :description="description ?? undefined"
        :ui="sectionUi"
    >
        <!-- Child blocks, rendered by PageRenderer into this slot. -->
        <slot />
    </u-page-section>
</template>

<script setup>
import { computed } from 'vue';

const props = defineProps({
    title: { type: String, default: null },
    description: { type: String, default: null },
    align: { type: String, default: 'left' },
    spacing: { type: String, default: 'normal' },
});

/**
 * `align` and `spacing` are bounded options in the block schema rather than
 * a pass-through of Nuxt UI's `ui` prop. Letting stored content supply `ui`
 * directly would hand it arbitrary classes on every slot of the component,
 * which is the same hole the props allowlist exists to close.
 *
 * Class strings are written out per option for the usual Tailwind reason:
 * an interpolated `py-${n}` is never generated by the scanner.
 */
const ALIGN_UI = {
    left: { container: 'text-left', title: 'text-left mx-0', description: 'text-left mx-0' },
    center: { container: 'text-center', title: 'text-center', description: 'text-center mx-auto' },
};

// UPageSection's own vertical rhythm is built for marketing pages. A text
// page reads as half-empty at that scale, so `compact` exists and is the
// default — a landing page opts into the roomier one.
const SPACING_UI = {
    compact: 'py-8 sm:py-10',
    normal: 'py-12 sm:py-16',
};

const sectionUi = computed(() => {
    const align = ALIGN_UI[props.align] ?? ALIGN_UI.left;
    const padding = SPACING_UI[props.spacing] ?? SPACING_UI.normal;

    return { ...align, container: `${align.container} ${padding}` };
});
</script>
